### ISSUE TITLE
Probably you should use helm-gtags

### ISSUE THREAD

**Issue by tuhdo** [kaushalmodi/.emacs.d#1]
I saw your issue on `ggtags`, so I will answer it hear. The answer is easy: since you already use Helm, use [helm-gtags](https://github.com/syohex/emacs-helm-gtags), it's really fast, since Helm buffer is basically `fundamental-mode`, unlike compilation buffer which contains text widgets, which is heavy when there are many entries to show.

**Comment by kaushalmodi** [comment]
Alright I give helm another go over the weekend. I was just about to rid of helm because I find `swiper` as a great alternative to `helm-swoop` (the only thing for which I had to keep helm installed). :)

Thanks for the tip; I'll update when I try it out.

**Comment by tuhdo** [comment]
Yes, even for over 10000 matches, `helm-gtags` shows you instantly. Tested. As for `swiper`, it still got a long way to go for async sources such as `helm-grep`, or `helm-gtags` in this case.

**Comment by kaushalmodi** [comment]
`helm-gtags` is fast! Thanks for the tip.

https://github.com/kaushalmodi/.emacs.d/commit/c08e5ac8edd3f7e628c1ada2eacc6372980c8fcb
