### ISSUE TITLE
How can I activate hydra-nav-error ?

### ISSUE THREAD

**Issue by smithx** [kaushalmodi/.emacs.d#14]
Are there any key binding to activate this hydra ?  I can't find.

[defhydra hydra-nav-error](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-navigation.el#L193)

**Comment by kaushalmodi** [comment]
Here I am using the "Style 1" method of binding hydra which is described [here](https://github.com/abo-abo/hydra/wiki/Binding-Styles#style-1-dont-mess-with-the-prefix).

``` el
(defhydra hydra-nav-error
  (nil "M-g"
       :bind (lambda (key cmd) (bind-key key cmd modi-mode-map))
       :color pink)
  "nav-error"
  ("g"        first-error    "first")
  ("n"        next-error     "next")
  ("p"        previous-error "prev")
  ("q"        nil            "cancel")
  ("<return>" nil            "cancel"))
```

Above means that the hydra is activated when I hit `M-g`. But it is "actually active" only for the listed heads: `g`, `n`, `p`, `q`, `<return>`. So the hints will appear only when I press one of these keys.

The reason for doing so is that I still want to preserve other emacs-default bindings that start with `M-g`, like `M-g c` for `goto-char`, `M-g M-g` for `goto-line`, etc.

So to answer your question in another way, you an activate this hydra by typing `M-g` followed by one of these: `g`, `n`, `p`, `q`, `<return>`.

**Comment by smithx** [comment]
Thank you very much, It is my fault, I must be "more RTFM"

**Comment by kaushalmodi** [comment]
Not a problem. Glad to help.
