### ISSUE TITLE
Add bash version of git_force_update.csh

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/.emacs.d#20]
https://github.com/kaushalmodi/.emacs.d/pull/19

**Comment by hhnr** [comment]
any reason you are using csh script in the first place?

**Comment by kaushalmodi** [comment]
@rdotdk work

**Comment by hhnr** [comment]
Work laptop? Okay. Let me guess RHEL?

**Comment by kaushalmodi** [comment]
> Work laptop?

Sort of, virtual machine.

> RHEL?

Yup

**Comment by kaushalmodi** [comment]
I went ahead and replaced `git_force_update.csh` with `force_update_emacsd.sh`.

https://github.com/kaushalmodi/.emacs.d/commit/646b859885f7980624e4504372540fd844adb8a3

In `tcsh`, I use this alias:

```
alias update_emacs_config '(set e="/tmp/${USER}_force_update_emacsd.sh" \\
                           && curl https://raw.githubusercontent.com/kaushalmodi/.emacs.d/master/force_update_emacsd.sh >! $e \\
                           && chmod 0755 $e \\
                           && $e \!:1)'
```

**Comment by hhnr** [comment]
@kaushalmodi the script seems to fail with `./force_update_emacsd.sh: [[: not found` error. I think the first line `#!/bin/sh` should be `#!/bin/bash`.

**Comment by kaushalmodi** [comment]
@rdotdk Thanks for trying. RHEL probably has `sh` symlinked to `bash`. So I didn't notice it. Let me see if I can use `[` instead of `[[`. If not, will change the shebang to `bash`.

**Comment by kaushalmodi** [comment]
> RHEL probably has `sh` symlinked to `bash`.

Of course it is :)

```
> sh --version       
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by kaushalmodi** [comment]
As I cannot try the "real sh" on my system, I am going with what you suggested.

@rdotdk Try out after updating to https://github.com/kaushalmodi/.emacs.d/commit/cc6e09dd5fcc863bb7d7d16dc2c5325e98693875

**Comment by hhnr** [comment]
Works without any errors. Tested with bash on Ubuntu system.

> RHEL probably has sh symlinked to bash.

In case of debian based systems it is symlinked to dash.

``` shell
hari@hari-laptop:~$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Nov  1 10:31 /bin/sh -> dash*
```

**Comment by kaushalmodi** [comment]
> Works without any errors. Tested with bash on Ubuntu system.

Thanks for confirming!

**Comment by kaushalmodi** [comment]
Note to self: **Never use `#!/bin/sh` in shebangs.**

**Comment by hhnr** [comment]
Yes. Also the paths shouldn't be mentioned directly in the shebang, instead `#!/usr/bin/env bash` should be used for portability.

**Comment by kaushalmodi** [comment]
Thanks, I was almost going to do that as I do the same for `perl`. I assumed that `bash` would be fine.

But there you go ( https://github.com/kaushalmodi/.emacs.d/commit/bd1131207035c3cf2032e78651febeea6e71e469 ). I cannot not do the right thing. :)
