### ISSUE TITLE
projectile is adding .git folders to the list of known projects

### ISSUE THREAD

**Issue by CSRaghunandan** [kaushalmodi/.emacs.d#21]
Projectile was working fine for as long as I remember, but I think one of the recent updates might have been causing a bug. Projectile adds `.git` folder as another known project whenever I invoke `magit` on a projectile project. Here is a screenshot :-

[![enter image description here][1]][1]

Here is the [link](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-projectile.el) to my projectile config. 

<hr>

  [1]: https://i.stack.imgur.com/pRh6J.png

**EDIT**: I figured out the cause of the issue. It's this code snippet :-
  

    ;; Git projects should be marked as projects in top-down fashion,
      ;; so that each git submodule can be a projectile project.
      (setq projectile-project-root-files-bottom-up
      	(delete ".git" projectile-project-root-files-bottom-up))
      (add-to-list 'projectile-project-root-files ".git")
    
      (setq projectile-project-root-files-functions
      	'(projectile-root-local
      	  projectile-root-top-down ; First look for projects in top-down order
      	  projectile-root-bottom-up)) ; Then in bottom-up order

looks like the new update to projectile is causing the probelm. What's going on here? Does the same thing happen to your config?

**Comment by kaushalmodi** [comment]
That code was last updated on July 29. I haven't seen the issue that you are seeing.

Here is what I see:
![image](https://cloud.githubusercontent.com/assets/3578197/20315275/4a88bfe0-ab2b-11e6-9916-46a6f15230cf.png)

The `.git` related code is so that I can see each git submodule as a separate project. That is not the case by default.

> Projectile adds .git folder as another known project whenever I invoke magit on a projectile project. 

What do you mean by that? The screenshot seems to be for `projectile-switch-project`. I use `magit` for this `.emacs.d` project and all the submodules.

**Comment by CSRaghunandan** [comment]
If i have any project version controlled by git, whenever I make changes and commit using magit, a new project is added to the list of projects which is the `.git` folder inside the project root. 

Take a look at `~/.emacs.d/.git/` in the image. Now I've both `~/.emacs.d/` and `~/.emacs.d/.git`. I have no idea why this is happening.

**Comment by kaushalmodi** [comment]
I cannot debug this as I cannot recreate the issue in my config. I would suggest that you remove that code if that's creating these `.git` 'projects', or even better: Run `edebug` to understand what piece of code in the `projectile` package is doing this.

**Comment by CSRaghunandan** [comment]
Cool, I'll just remove the code which is causing the issue for now.
