### ISSUE TITLE
Dedicated repo for eless?

### ISSUE THREAD

**Issue by alphapapa** [kaushalmodi/.emacs.d#25]
Hey, I just saw your blog post about eless, and it looks very cool!  What do you think about putting it in a separate repo?  :)

**Comment by kaushalmodi** [comment]
[Done!][1] -- I was on the fence for this, because if I did it, I wanted to do it cleanly and that needed re-writing git commit history in this repo. Well, it's done now : )

[1]: https://github.com/kaushalmodi/eless
