### ISSUE TITLE
Error modi/temporary-file-directory

### ISSUE THREAD

**Issue by yuravg** [kaushalmodi/.emacs.d#30]
Hi,
I don't have variable 'USER':

`
(defvar modi/temporary-file-directory (let* ((dir (file-name-as-directory (expand-file-name (getenv "USER") temporary-file-directory))))
                                        (make-directory dir :parents)
                                        dir)
  "User-specific temporary directory name.")
`

probably on this emacs start ends with error(Windows OS):

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "c:/Users/MYNAME~1/AppData/Local/Temp/")Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil "c:/Users/MYNAME~1/AppData/Local/Temp/")`

**Comment by kaushalmodi** [comment]
Hmm, I don't see this issue. May be you just need to set the USER environment variable in Windows. I'm not a Windows expert, but here are instructions I found online for setting PATH variable: https://www.java.com/en/download/help/path.xml. Follow the same for setting USER.

**Comment by kaushalmodi** [comment]
Can you tell me what you get on doing `C-h v user-login-name` (without setting the USER environment variable)?

**Comment by kaushalmodi** [comment]
.. that's without setting the USER environment variable.

**Comment by yuravg** [comment]
> Can you tell me what you get on doing C-h v user-login-name (without setting the USER environment variable)?

Оf course, but I can't do it until Monday.
(now there is only Debian)

> ...Follow the same for setting USER.

Ok, I will tray it(when I get to Windows OS),
for a while I did so

`(defvar modi/temporary-file-directory (let* ((dir (file-name-as-directory (expand-file-name "tmp" (getenv "HOME")))))
                                        (make-directory dir :parents)
                                        dir)
  "User-specific temporary directory name.")
`

**Comment by kaushalmodi** [comment]
@yuravg If you update to the latest master branch of this repo, this issue should be resolved now. I am now using `user-login-name` which is auto-derived from the `USERNAME` env var for windows (but from `USER` env var on GNU/Linux and other systems).

**Comment by yuravg** [comment]
Thank you,
when I try in the Windows OS, I'll immediately write about the result

**Comment by yuravg** [comment]
> Can you tell me what you get on doing C-h v user-login-name (without setting the USER environment variable)?

My login name.

>If you update to the latest master branch of this repo, ...

It works from Window/Run and minGW (without additional env).
Thank you for your help, and excellent .emacs.d

**Comment by kaushalmodi** [comment]
That's great! Thanks for the kind words :)
