### ISSUE TITLE
Opening executable tcl-files

### ISSUE THREAD

**Issue by yuravg** [kaushalmodi/.emacs.d#36]
Hi,

When I open executable tcl-files, they open in sh-script mode, because
the first line of these files has the line: `#!/bin/sh`

As written in the https://tcl.tk/doc/styleGuide.pdf,
I use
`#!/bin/sh`
`#\`
`exec tclsh"$0" "$@"`

May you improve setup-shell.el to solve this?

**Comment by kaushalmodi** [comment]
Hello, this auto detection happens using the built-in sh-mode. 

The style guide indeed shows a weird way to write the Tcl shebang that I have never seen before. 

Does this work?

```
#!/usr/bin/env tclsh
```

**Comment by kaushalmodi** [comment]
Found this:

https://rosettacode.org/wiki/Multiline_shebang

> Warning: Using a multiline shebang of the form #!/bin/sh ... exec ... !# will set the code's mimetype to text/x-shellscript, which creates problems such as Emacs treating the file as a shell script, no matter which language and file extension it really uses. 

So, if the single line shebang above works, see you can do by that, otherwise, you might need to look into parsing the multiline shebang.

**Comment by kaushalmodi** [comment]
Interesting https://wiki.tcl-lang.org/page/Tcl+Style+Guide mentions the usr bin env version of the shebang too:

> Another common method seen is to use:

> `#!/usr/bin/env tclsh`

> Then you can just do a package require Tk if Tk is actually needed. Your mileage may vary on using this one and you may run into trouble if you have multiple installs of Tcl/Tk.

**Comment by yuravg** [comment]
I see.

`#!/usr/bin/env tclsh` or `#!/usr/bin/env wish`
it works, I will use them

Thank you!

**Comment by kaushalmodi** [comment]
Great! Closing this issue then.
