### ISSUE TITLE
Changing the hugo mode load

### ISSUE THREAD

**Issue by yuravg** [kaushalmodi/.emacs.d#37]
Hi,
There are no way to run your emacs configuration without loaded ox-hugo (git-submodule)

> Warning (initialization): An error occurred while loading ‘c:/HOME/.emacs.d/init.el’:
>File is missing: Opening directory, No such file or directory, c:/HOME/.emacs.d/elisp/ox-hugo/
>To ensure normal operation, you should investigate and remove the
>cause of the error in your initialization file.  Start Emacs with
>the ‘--debug-init’ option to view a complete error backtrace.

maybe it doesn't matter, but sometimes it is inconvenient

**Comment by kaushalmodi** [comment]
OK, I am now requiring `setup-hugo` only if the `hugo` binary is found in PATH.

Please git pull; that should resolve this issue. Comment here if it doesn't.
