### ISSUE TITLE
Loading 'iy-go-to-char' package

### ISSUE THREAD

**Issue by yuravg** [kaushalmodi/.emacs.d#43]
Hi,
[iy-go-to-char](https://github.com/doitian/iy-go-to-char) package no longer available in [MELPA](https://melpa.org/#/iy-go-to-char).

maybe it is no longer needed?

**Comment by kaushalmodi** [comment]
Thanks. I do use iy-go-to-char even now. I have now added that package to manually maintained section of my repo.
