### ISSUE TITLE
Loading 'interleave' package

### ISSUE THREAD

**Issue by yuravg** [kaushalmodi/.emacs.d#44]
Hi,
 package  [interleave](https://github.com/rudolfochrist/interleave) no longer available in [MELPA](https://melpa.org/#/interleave).

**Comment by kaushalmodi** [comment]
Yes, I am aware that that package is not maintained any more.

That repo says:

> This package is not maintained anymore. User should go and checkout weirdNox/org-noter as an alternative.

I'll try out `org-noter` and replace `interleave` with that.
